### PR TITLE
faster hexToDec

### PR DESCRIPTION
**Pull request by mrubioroy**

### CODE REVIEW

**Comment by nickn17** [comment]
There is and error with 4 byte conversion
CHECKING... OLD vs NEW FFAABBCC
DIFF UNSIGNED 4289379276.00 vs 2147483647.00
DIFF SIGNED -5587968.00 vs 2147483646.00

**Comment by ilachEU** [comment]
Both negative values are incorrect. The correct one is -5588020.00
Fix for original / old conversion: delete variable retyping `(float)`
(float stores only 6 significant digits, that's not enough, so the result is inaccurate)
Fix for new: `range` to `double` and `range = pow (256, bytes);`
(Bit conversion does not work as expected. `1 << 32` is 33 bits in BIN. Long is 32 bit with a sign, so the expected result is up to `1 << 30`)
https://wokwi.com/arduino/projects/321219810134327890

**Comment by nickn17** [comment]
PR accepted, going to do small fixes. Uint64_t will be better that double for range, ok ?

  **uint64_t** range;
  double decValue = **strtoll**(hexString.c_str(), NULL, 16);
  if (signedNum)
  {
    **range = pow(256, bytes);**
    if (decValue > (range - 1) / 2)
      decValue -= range;
  }
  if (bytes < 1 || bytes > 4)
    return -1;
  else
    return decValue;

**Comment by nickn17** [comment]
Btw good job. This will be much faster. Thank you.

**Comment by mrubioroy** [comment]
I was writing you a message this morning with the fixed version but I got interrupted. I’ll send it to you later today. It’s better to use range as integer to reduce the number of floating point operations. 

Miguel

**Comment by mrubioroy** [comment]
Besides the float and double bug, there was another one also in the original code:
```
case 4:
    return (decValue > 3147483647 ? (float)decValue - 4294967296.0 : decValue);
```
should be:
```
case 4:
    return (decValue > 2147483647 ? (double)decValue - 4294967296.0 : decValue);
```
There's a typo "3" instead of "2" for the switch to signed values.

**Pull request merged**
